### ISSUE TITLE
X-platform consistent and pleasant DevX

### ISSUE THREAD

**Issue by scottmuc** [scottmuc/infrastructure#50]
A chat with some friends started with a post about monospace font selection: https://www.tbray.org/ongoing/When/202x/2023/02/09/Monospace

Given all the workstation automation I have, I can't say I'm satisfied with my devx (development experience). It's ok, but it's got some issues that I'd like to improve.

Objectives:

* [x] Setup system that allows for easy swapping of fonts and themes (to better evaluate)
* [x] Choose and configure a consistent font to be used
* [x] Swap between dark and light consistently and without too much duct-tape
* [x] Ensure readable font size for my aging eyes

**Comment by scottmuc** [comment]
Learning that [NerdFonts](https://www.nerdfonts.com/) is the one-stop-shop for font related packages.

[programmingfonts.org](https://www.programmingfonts.org/) is a great place to preview them. So far I'm liking:

[JetBrains Mono](https://www.programmingfonts.org/#jetbrainsmono) - leaning towards this because I prefer how the l (el) is easy to differentiate between a 1 (one) and I (capital i). I prefer the styling of the g as well.
[Roboto Mono](https://www.programmingfonts.org/#roboto)
[Inconsolata-g](https://www.programmingfonts.org/#inconsolata-g)
[Inconsolata](https://www.programmingfonts.org/#inconsolata) - handles narrower screens better. It's inspired by Consolas which is something I've always liked on Windows

I'm on the fence about combined ligatures ( => turning into a single character).

I'll start with installing all 4 of these for now.

**Comment by lurraca** [comment]
For a font to use on the console, check out this one: https://sourcefoundry.org/hack/

**Comment by scottmuc** [comment]
@lurraca, I checked out `hack` but didn't find it any more special than the ones I already mentioned.

**Comment by scottmuc** [comment]
Content that the commits up until now ensure that I have `JetBrainsMono NF` used in my macOS terminal (via Alacritty), Windows terminal (via Alacritty), and in VS Code. Future repaves should ensure that this is all setup appropriately.

Alacritty configuration management is revealing where `asdf` can cause confusion. Since `alacritty-colorscheme` is a `python` module. The directory of my `$PWD` matters. The current tooling is installing it in the `python` in my `~/workspace/infrastructure` repo's `.tool-versions`. While I believe this should be a user level thing. Thankfully, the error mode isn't damaging, and the `asdf` shimming implementation (see #49 ) does communicate what's happening well enough.

**Comment by scottmuc** [comment]
Happy enough with the current light/dark theme switching.

In Windows, if I switch modes, VSCode will follow. In WSL, I can run `night/day` functions to change Allacrity/Neo Vim/Delta colours.

On macOS, it's the same as WSL.

I'm on the fence about Solarized. I feel that my eyes need something with a bit more contrast.

**Comment by scottmuc** [comment]
Conformed around 16pt font for VSCode and terminal. It's large and easy for me to read, but the rest of the VSCode chrome doesn't follow suit.

**Comment by scottmuc** [comment]
* [ ] record a showcase video, then this is done

**Comment by scottmuc** [comment]
Recording of showcase is: https://youtu.be/y817A1SemNA (currently processing)

**Comment by scottmuc** [comment]
A friend mentioned https://github.com/chriskempson/base16-shell which might be an alternative to the alacritty color scheme stuff I'm doing. Something to try in a future issue.

**Comment by mamachanko** [comment]
As far as color schemes go, I have found [catpuccin](https://catppuccin.com/) to be both soothing for the eyes and the brain, knowing that almost every conceivable _thing_ with a UI is supported by its community. [Nord](https://www.nordtheme.com/) is similar.

**Comment by scottmuc** [comment]
@mamachanko, ooh I really like those! Now that I have a consistent way to switch between dark/light modes, I think I'd like to incorporate a theme switch with it as well... though the switching is mainly for testing than the desire to switch themes depending on my mood (dark/light modes are more around their function than their ascetic). Thanks!
