### ISSUE TITLE
Migrate to lua configuration for NeoVim

### ISSUE THREAD

**Issue by scottmuc** [scottmuc/infrastructure#63]
I'm finding NeoVim a lot more mature now. The idea of porting the configuration to a general purpose language like `lua` that's used in other environments is appealing. Plus, future integrations should be less painful too.

* [NeoVim IDE from Scratch](https://www.youtube.com/watch?v=ctH-a-1eUME&list=PLhoH5vyxr6Qq41NFL4GvhFp-WLd5xzIzZ)
* [Nat Bennett's intro post](https://www.simplermachines.com/build-your-own-vim-config/)
* [Primeagen's 0 to LSP from scratch](https://www.youtube.com/watch?v=w7i4amO_zaE)

Have to give respect to the `vimscript` configuration that has been used for a long time.

Why not use some out-of-the-box NeoVim (like [LunarVim](https://www.lunarvim.org/))? I love those when I'm in a work environment where everyone shares the configuration (❤️ Pivotal). In that type of environment, the activity of pairing brings you up to speed rapidly (we used [luan's vimfiles](https://github.com/luan/vimfiles)). The intention of this task is not to do this quickly. It's going to be a slow-plod while I learn and get better at my tools. My skills have atrophied a bit over the last years.

**Comment by scottmuc** [comment]
Getting some inspiration from https://github.com/ThePrimeagen/init.lua but don't feel the need to create a user specific configuration. I think `init.lua` is fine for holding all the remaps and config settings. I will do the package separation configuration though. I find that rather cohesive. Removing the package, therefore also remove the package specific configuration file.

Packer does look much more complex that all the previous `vim` package configuration I've used in the past, but I'm accepting that as a necessary complexity to reach the more IDE like functionality.

**Comment by scottmuc** [comment]
I'm happy that I've removed `jk` as my `<Esc>` mapping. I've been in the habit of hitting `jkjkjkjkjkjkjkjk` on repeat. I'll stick with `<Esc>` until a something else feels better.

**Comment by scottmuc** [comment]
Some handy resources I've found along the way:

* https://www.imaginaryrobots.net/posts/2021-04-17-converting-vimrc-to-lua/
* https://neovim.io/doc/user/lua-guide.html#lua-guide-config
* https://github.com/nanotee/nvim-lua-guide
* https://herrbischoff.com/2022/07/neovim-using-init-vim-and-init-lua-concurrently/

**Comment by scottmuc** [comment]
So far got `packer` working. I stripped out the machine automation from `coalesce_this_machine`. I feel like I want to be a bit more hands on with this. So bootstrapping a new environment will have a few more commands to run. The `init.lua` will still be symlinked so it should be easy. Things that need to run:

* Cloning the `packer` as per the [Quickstart](https://github.com/wbthomason/packer.nvim#quickstart)
* Launching `nvim` and running `:PackerSync`
* Quitting and relaunching to ensure no errors.

I think I can live with those steps for now.

**Comment by scottmuc** [comment]
When trying to configure `telescope` it complained that my version if `nvim` is too old (running `0.5`). To upgrade, I followed the instructions here: https://launchpad.net/~neovim-ppa/+archive/ubuntu/stable

I've been using `<C + p>` as my shortcut for a while so this might take a little getting used to. I went with the keymaps that they suggested: https://github.com/nvim-telescope/telescope.nvim#usage

**Comment by mamachanko** [comment]
https://lunarvim.org is my workhorse 🐴

**Comment by scottmuc** [comment]
@mamachanko I can see myself switching to that at some point. So far this has been a good exercise is learning the `lua` configuration method and getting acquainted to the plugins that this new configuration strategy has enabled.

**Comment by scottmuc** [comment]
With `treesitter` and `lsp` stuff I'm seeing some issues.

* `Mason` is failing to install language servers because it cannot execute `npm`. It looks like I need to add a `nodejs` runtime to my system to get this to work.
* I like using `git` from the CLI and having an LSP and treesitter trying to do stuff in the commit buffer is annoying. I'm sure there's a way to prevent that from happening.
* Not getting the indention that I wanted (and expected from `vim-sleuth`.
* I need to `:w!` for files opened with `telescope` in order to save them.

Also noticed that `LSP Zero` has a version `v2` but requires `neovim` `> 0.8`. So I might be in for a "fun" upgrade.

At this point, `tree-sitter` and `lsp-zero` have fulled in a ton of stuff. I've lost my `terraform` highlighting so I'll try and get that back.

**Comment by scottmuc** [comment]
After upgrading to `neovim` `v0.10.0-dev`, and installing `nodejs` with `nvm`. Things are working really well! The `bashls` is working great for my bash scripts. My `.editorconfig` is handled by `neovim` itself (as of `>= 0.9.x`). The files I open with `telescope` don't require me to use `:w!` to save. My `*.tf` files.

Things to look at documenting/automating:

* Configuring `apt` to install `neovim` from `unstable` repo to get latest version.
* Add `nvm` installation to workstation automation. Or possibly use `asdf` to manage `nodejs` at the user level (and only use `nvm` for project level setup.

**Comment by scottmuc** [comment]
Thankfully `v2.x` of `lsp-zero` is working, but it appears that `v3.x` is going to break a lot of my configuration (https://github.com/VonHeikemen/lsp-zero.nvim#future-changesdeprecation-notice). Something to keep in mind in a few months.

**Comment by scottmuc** [comment]
# Summary

I've [published a demo video](https://www.youtube.com/watch?v=UPyNOw1_z-U) (20m) displaying the results of this migration.

Upon completing this, it really solidified in my head the core components of a good editor experience:

* good navigation capabilities (find a file, find text in files, go to definitions, etc...)
* easy to look at syntax highlighting and informational details
* real time code analysis (linting, formatting, etc...)
* code completion (through snippets, or real time analysis of the project code)
* key-bindings to do all-of-the-above quickly

NeoVim shines by being able to store the configuration in a repo and be able to write the configuration in `lua`. I can configure it to be as noisy or as quiet as I prefer.

**Comment by thenbe** [comment]
This randomly popped up on my yt feed.

Bad news is packer is more or less [dead](https://github.com/wbthomason/packer.nvim/issues/1229). Good news is that there is a better [replacement](https://github.com/folke/lazy.nvim)  You *can* start with it [like this](https://www.lazyvim.org/), which gives you immediate access to [this](https://www.lazyvim.org/extras/lang/terraform). But since you're intentionally taking it slow [this](https://github.com/nvim-lua/kickstart.nvim) might be a better fit. Good luck!

**Comment by scottmuc** [comment]
Thanks @thenbe! I recently learnt about `kickstart.nvim` after the video released. I love over-explained configuration for learning. I'll look at `lazy.nvim` and switch. This ecosystem is moving so fast!

**Comment by scottmuc** [comment]
With the above commit, the video is out-of-date. I think this is what I like about attaching a GitHub issue to the video. The code is always "latest" while a video/tutorial/quickstart is often a snapshot in time.
